### ISSUE TITLE
Being flung over to the other side of the map 

### ISSUE THREAD

**Issue by infamouspotatofpv** [taylorgoolsby/fpv-drone-issue-tracker#1]
Hey when i am put into fpv mode sometimes it speeds up and sending my flying way too fast is this any easy fix

**Comment by taylorgoolsby** [comment]
Working on this now

**Comment by infamouspotatofpv** [comment]
great cant wait to see it fixed it seems to happen when chunks are trying to be loaded

**Comment by taylorgoolsby** [comment]
fixed on 1.1.1!

Download: https://www.curseforge.com/minecraft/mc-mods/fpv-drone/files/2984181

**Comment by infamouspotatofpv** [comment]
the channels arnt working in the newest update (xlite)
