### ISSUE TITLE
dosnt work with flysky i6x

### ISSUE THREAD

**Issue by neenong** [taylorgoolsby/fpv-drone-issue-tracker#3]
the transmitter i am using only has 10 channels so i cannot set arm to 12 channel

**Comment by taylorgoolsby** [comment]
Ok in game settings is done now. You can bind your axis by clicking the channel button then moving the axis. Minecraft will detect will axis you moved and assign it to that channel.

Download 1.1.0: https://www.curseforge.com/minecraft/mc-mods/fpv-drone/files
